### ISSUE TITLE
Replace ConstantChaumPedersenProofKnownNonce with RangeChaumPedersenProofKnownNonce

### ISSUE THREAD

**Issue by JohnLCaron** [danwallach/electionguard-kotlin-multiplatform#171]
I think we could also replace DisjunctiveChaumPedersenProofKnownNonce with RangeChaumPedersenProofKnownNonce,

should we?

**Comment by danwallach** [comment]
Every disjunctive proof should be replaced with a range proof. That's a no-brainer.

So far as I can tell, we use a constant-proof-known-nonce in exactly one circumstance: proving that the sum of the counters in a contest is equal to a constant. Once we get rid of the placeholders, this becomes a range proof, since the sum of all of them in a k-of-n constant will be in the range 0-to-k (inclusive).

**Comment by danwallach** [comment]
Redundant with #152 , so closing this as a dup.
